# Day 3

In [1]:
import numpy as np

## Answer 1

In [2]:
np.arange(2,51,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

## Answer 2

#### Function to read lists

In [16]:
def readList():
    lst = []
    for i in range(5):
        lst.append(input())
    return lst

### Converting lists to numpy arrays

In [17]:
lst1 = readList()
lst2 = readList()

arr1 = np.array(lst1)
arr2 = np.array(lst2)

print(arr1)
print(arr2)

1
2
3
4
5
6
8
9
7
12
['1' '2' '3' '4' '5']
['6' '8' '9' '7' '12']


### Concatenating these arrays

In [25]:
arr = np.concatenate((arr1,arr2))
arr

array(['1', '2', '3', '4', '5', '6', '8', '9', '7', '12'], dtype='<U2')

### Sorting the new array

In [29]:
arr.sort()
arr

array(['1', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U2')

## Answer 3

In [37]:
a = np.random.randint(0,10,12).reshape(4,3)
a

array([[4, 1, 8],
       [7, 3, 9],
       [3, 3, 5],
       [1, 3, 5]])

In [47]:
dimension = a.shape
size = a.size
print('Dimension:',dimension)
print('Size:',size)

Dimension: (4, 3)
Size: 12


## Answer 4

In [50]:
a = np.random.randint(0,10,12)
a

array([0, 7, 8, 3, 8, 8, 7, 9, 9, 4, 5, 0])

In [54]:
a[:,np.newaxis]

array([[0],
       [7],
       [8],
       [3],
       [8],
       [8],
       [7],
       [9],
       [9],
       [4],
       [5],
       [0]])

In [68]:
np.expand_dims(a,1)

array([[0],
       [7],
       [8],
       [3],
       [8],
       [8],
       [7],
       [9],
       [9],
       [4],
       [5],
       [0]])

## Answer 5

In [78]:
sqr1 = np.random.randint(0,10,9).reshape(3,3)
sqr2 = np.random.randint(0,10,9).reshape(3,3)
print(sqr1)
print(sqr2)

[[4 9 6]
 [1 4 0]
 [5 7 7]]
[[0 5 8]
 [9 5 9]
 [7 9 2]]


In [80]:
print(np.vstack((sqr1,sqr2)))
print(np.hstack((sqr1,sqr2)))

[[4 9 6]
 [1 4 0]
 [5 7 7]
 [0 5 8]
 [9 5 9]
 [7 9 2]]
[[4 9 6 0 5 8]
 [1 4 0 9 5 9]
 [5 7 7 7 9 2]]


## Answer 6

In [91]:
a

array([0, 7, 8, 3, 8, 8, 7, 9, 9, 4, 5, 0])

In [84]:
np.unique(a)

array([0, 3, 4, 5, 7, 8, 9])

In [89]:
np.unique(a,return_counts = True)

(array([0, 3, 4, 5, 7, 8, 9]), array([2, 1, 1, 1, 2, 3, 2]))